begin;

create extension if not exists pgcrypto;

do $$
begin
  create type public.app_role as enum ('customer', 'admin');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.order_status as enum (
    'pending',
    'confirmed',
    'preparing',
    'ready',
    'out_for_delivery',
    'completed',
    'cancelled'
  );
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.fulfillment_type as enum ('pickup', 'delivery');
exception when duplicate_object then null;
end $$;

do $$
begin
  create type public.payment_status as enum ('pending', 'paid', 'failed', 'refunded');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role public.app_role not null default 'customer',
  display_name text,
  phone text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_categories (
  id text primary key,
  title text not null,
  subtitle text,
  note_de text,
  note_en text,
  image_path text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  category_id text not null references public.menu_categories(id) on delete cascade,
  item_number integer not null unique,
  name text not null,
  description_de text,
  description_en text,
  price numeric(10,2) not null check (price >= 0),
  image_path text,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.site_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  description text,
  is_public boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.content_blocks (
  key text primary key,
  title text,
  body text,
  data jsonb not null default '{}'::jsonb,
  is_published boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.opening_hours (
  weekday smallint primary key check (weekday between 0 and 6),
  day_of_week smallint generated always as (weekday) stored,
  is_closed boolean not null default false,
  lunch_opens time,
  lunch_closes time,
  dinner_opens time,
  dinner_closes time,
  open_time time generated always as (lunch_opens) stored,
  close_time time generated always as (lunch_closes) stored,
  second_open_time time generated always as (dinner_opens) stored,
  second_close_time time generated always as (dinner_closes) stored,
  note text,
  updated_at timestamptz not null default now(),
  constraint opening_hours_lunch_pair check (
    (lunch_opens is null and lunch_closes is null)
    or (lunch_opens is not null and lunch_closes is not null and lunch_opens < lunch_closes)
  ),
  constraint opening_hours_dinner_pair check (
    (dinner_opens is null and dinner_closes is null)
    or (dinner_opens is not null and dinner_closes is not null and dinner_opens < dinner_closes)
  ),
  constraint opening_hours_closed_has_no_times check (
    not is_closed
    or (lunch_opens is null and lunch_closes is null and dinner_opens is null and dinner_closes is null)
  )
);

create table if not exists public.store_availability (
  id boolean primary key default true check (id),
  accepts_orders boolean not null default true,
  pickup_enabled boolean not null default true,
  delivery_enabled boolean not null default true,
  minimum_notice_minutes integer not null default 30 check (minimum_notice_minutes >= 0),
  paused_reason text,
  updated_at timestamptz not null default now()
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text not null unique default (
    to_char(now(), 'MMDD') || '-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 4))
  ),
  confirmation_token uuid not null unique default gen_random_uuid(),
  idempotency_key text unique,
  user_id uuid references auth.users(id) on delete set null,
  status public.order_status not null default 'pending',
  fulfillment_type public.fulfillment_type not null,
  payment_status public.payment_status not null default 'pending',
  payment_method text not null default 'cash',
  payment_provider text,
  payment_reference text,
  accepted_no_cancellation boolean not null default false,
  currency text not null default 'CHF' check (currency = upper(currency) and char_length(currency) = 3),
  subtotal numeric(10,2) not null check (subtotal >= 0),
  delivery_fee numeric(10,2) not null default 0 check (delivery_fee >= 0),
  total numeric(10,2) not null check (total >= 0 and total = subtotal + delivery_fee),
  customer_name text not null,
  customer_email text not null,
  customer_phone text not null,
  address_line1 text,
  address_line2 text,
  postal_code text,
  city text,
  delivery_address jsonb,
  customer_notes text,
  customer_note text generated always as (customer_notes) stored,
  requested_for timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint delivery_address_required check (
    fulfillment_type <> 'delivery'
    or address_line1 is not null
    or (delivery_address is not null and jsonb_typeof(delivery_address) = 'object')
  )
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id bigint references public.menu_items(id) on delete set null,
  item_number integer,
  name text not null,
  item_name text generated always as (name) stored,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10,2) not null check (line_total >= 0 and line_total = unit_price * quantity),
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.order_status_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  from_status public.order_status,
  to_status public.order_status not null,
  changed_by uuid references auth.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create index if not exists menu_categories_active_sort_idx
  on public.menu_categories (is_active, sort_order);
create index if not exists menu_items_category_sort_idx
  on public.menu_items (category_id, is_active, sort_order);
create index if not exists orders_user_created_idx
  on public.orders (user_id, created_at desc);
create index if not exists orders_status_created_idx
  on public.orders (status, created_at desc);
create index if not exists order_items_order_idx
  on public.order_items (order_id);
create index if not exists order_status_events_order_created_idx
  on public.order_status_events (order_id, created_at);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to anon, authenticated;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name, phone)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'name'),
    new.raw_user_meta_data ->> 'phone'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

create or replace function public.protect_profile_role()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.role is distinct from old.role
    and coalesce((select auth.role()), 'service_role') <> 'service_role'
    and not public.is_admin()
  then
    raise exception 'Only administrators may change profile roles';
  end if;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

drop trigger if exists protect_profile_role on public.profiles;
create trigger protect_profile_role
  before update on public.profiles
  for each row execute function public.protect_profile_role();

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'profiles',
    'menu_categories',
    'menu_items',
    'site_settings',
    'content_blocks',
    'opening_hours',
    'store_availability',
    'orders'
  ]
  loop
    execute format('drop trigger if exists set_%I_updated_at on public.%I', table_name, table_name);
    execute format(
      'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
      table_name,
      table_name
    );
  end loop;
end $$;

create or replace view public.store_settings
with (security_invoker = true)
as
select
  'default'::text as id,
  coalesce((select value #>> '{}' from public.site_settings where key = 'restaurant_name'), 'Safran') as restaurant_name,
  (select value #>> '{}' from public.site_settings where key = 'contact_email') as email,
  (select value #>> '{}' from public.site_settings where key = 'contact_phone') as phone,
  (select value #>> '{}' from public.site_settings where key = 'address') as address,
  coalesce((select (value #>> '{}')::numeric from public.site_settings where key = 'delivery_minimum'), 0) as minimum_order,
  coalesce((select (value #>> '{}')::numeric from public.site_settings where key = 'pickup_minimum'), 0) as pickup_minimum,
  coalesce((select (value #>> '{}')::numeric from public.site_settings where key = 'delivery_fee'), 0) as delivery_fee,
  coalesce((select accepts_orders from public.store_availability where id), false) as is_open,
  coalesce((select pickup_enabled from public.store_availability where id), false) as pickup_enabled,
  coalesce((select delivery_enabled from public.store_availability where id), false) as delivery_enabled,
  coalesce((select minimum_notice_minutes from public.store_availability where id), 30) as minimum_notice_minutes,
  (select paused_reason from public.store_availability where id) as closed_message;

create or replace function public.create_cash_order(p_order jsonb, p_items jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  created public.orders;
begin
  insert into public.orders (
    order_number,
    confirmation_token,
    idempotency_key,
    status,
    fulfillment_type,
    payment_status,
    payment_method,
    accepted_no_cancellation,
    customer_name,
    customer_email,
    customer_phone,
    address_line1,
    address_line2,
    postal_code,
    city,
    customer_notes,
    subtotal,
    delivery_fee,
    total,
    currency
  )
  values (
    p_order ->> 'order_number',
    (p_order ->> 'confirmation_token')::uuid,
    p_order ->> 'idempotency_key',
    (p_order ->> 'status')::public.order_status,
    (p_order ->> 'fulfillment_type')::public.fulfillment_type,
    (p_order ->> 'payment_status')::public.payment_status,
    p_order ->> 'payment_method',
    coalesce((p_order ->> 'accepted_no_cancellation')::boolean, false),
    p_order ->> 'customer_name',
    p_order ->> 'customer_email',
    p_order ->> 'customer_phone',
    p_order ->> 'address_line1',
    p_order ->> 'address_line2',
    p_order ->> 'postal_code',
    p_order ->> 'city',
    p_order ->> 'customer_notes',
    (p_order ->> 'subtotal')::numeric,
    (p_order ->> 'delivery_fee')::numeric,
    (p_order ->> 'total')::numeric,
    coalesce(p_order ->> 'currency', 'CHF')
  )
  returning * into created;

  insert into public.order_items (
    order_id,
    menu_item_id,
    name,
    quantity,
    unit_price,
    line_total,
    notes
  )
  select
    created.id,
    (item ->> 'menu_item_id')::bigint,
    item ->> 'name',
    (item ->> 'quantity')::integer,
    (item ->> 'unit_price')::numeric,
    (item ->> 'line_total')::numeric,
    item ->> 'notes'
  from jsonb_array_elements(p_items) as item;

  insert into public.order_status_events (order_id, from_status, to_status, note)
  values (created.id, null, created.status, 'Bestellung eingegangen');

  return jsonb_build_object(
    'id', created.id,
    'order_number', created.order_number,
    'confirmation_token', created.confirmation_token,
    'status', created.status,
    'total', created.total
  );
exception
  when unique_violation then
    select * into created
    from public.orders
    where idempotency_key = p_order ->> 'idempotency_key';

    if found then
      return jsonb_build_object(
        'id', created.id,
        'order_number', created.order_number,
        'confirmation_token', created.confirmation_token,
        'status', created.status,
        'total', created.total
      );
    end if;
    raise;
end;
$$;

revoke all on function public.create_cash_order(jsonb, jsonb) from public;
grant execute on function public.create_cash_order(jsonb, jsonb) to service_role;

alter table public.profiles enable row level security;
alter table public.menu_categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.site_settings enable row level security;
alter table public.content_blocks enable row level security;
alter table public.opening_hours enable row level security;
alter table public.store_availability enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_events enable row level security;

create policy "Profiles are visible to their owner or admins"
  on public.profiles for select
  to authenticated
  using ((select auth.uid()) = id or public.is_admin());
create policy "Users update their profile and admins update any profile"
  on public.profiles for update
  to authenticated
  using ((select auth.uid()) = id or public.is_admin())
  with check ((select auth.uid()) = id or public.is_admin());
create policy "Admins create profiles"
  on public.profiles for insert
  to authenticated
  with check (public.is_admin());
create policy "Admins delete profiles"
  on public.profiles for delete
  to authenticated
  using (public.is_admin());

create policy "Active menu categories are public"
  on public.menu_categories for select
  to anon, authenticated
  using (is_active);
create policy "Admins manage menu categories"
  on public.menu_categories for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Active menu items are public"
  on public.menu_items for select
  to anon, authenticated
  using (is_active);
create policy "Admins manage menu items"
  on public.menu_items for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Public site settings are readable"
  on public.site_settings for select
  to anon, authenticated
  using (is_public);
create policy "Admins manage site settings"
  on public.site_settings for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Published content blocks are public"
  on public.content_blocks for select
  to anon, authenticated
  using (is_published);
create policy "Admins manage content blocks"
  on public.content_blocks for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Opening hours are public"
  on public.opening_hours for select
  to anon, authenticated
  using (true);
create policy "Admins manage opening hours"
  on public.opening_hours for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Store availability is public"
  on public.store_availability for select
  to anon, authenticated
  using (true);
create policy "Admins manage store availability"
  on public.store_availability for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Customers read only their orders"
  on public.orders for select
  to authenticated
  using ((select auth.uid()) = user_id or public.is_admin());
create policy "Admins manage orders"
  on public.orders for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Customers read only items from their orders"
  on public.order_items for select
  to authenticated
  using (
    exists (
      select 1
      from public.orders
      where orders.id = order_items.order_id
        and (orders.user_id = (select auth.uid()) or public.is_admin())
    )
  );
create policy "Admins manage order items"
  on public.order_items for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Customers read status history for their orders"
  on public.order_status_events for select
  to authenticated
  using (
    exists (
      select 1
      from public.orders
      where orders.id = order_status_events.order_id
        and (orders.user_id = (select auth.uid()) or public.is_admin())
    )
  );
create policy "Admins manage order status history"
  on public.order_status_events for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'menu-images',
  'menu-images',
  true,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp', 'image/avif']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy "Menu images are publicly readable"
  on storage.objects for select
  to public
  using (bucket_id = 'menu-images');
create policy "Admins upload menu images"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'menu-images' and public.is_admin());
create policy "Admins update menu images"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'menu-images' and public.is_admin())
  with check (bucket_id = 'menu-images' and public.is_admin());
create policy "Admins delete menu images"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'menu-images' and public.is_admin());

commit;
